# Server configuration
server:
  host: "192.168.1.1"
  port: 51820
  dns: "1.1.1.1"
  interface_address: "172.16.0.1/24"
  allowedIPs: "10.0.0.0/20"
  private_key: "/etc/wireguard/privatekey"
  public_key: "/etc/wireguard/publickey"
  preshared_key: "/etc/wireguard/preshared"
  log_file: "wgclient.log"

# API configuration
api:
  host: "https://example.net"
  user: "foo"
  pass: "bar"
  basic_user: "john"
  basic_pass: "doh"
  query_frequency: 10 # in seconds

# API endpoints
api_endpoints:
  config_update: "/api/config/update"
  session_create: "/api/session/create"
  keypair_list: "/api/keypair/import"